"use client"

import { useState } from "react"
import type { DesignElement } from "@/lib/types"

interface ExportPanelProps {
  code: string
  elements: DesignElement[]
}

export default function ExportPanel({ code, elements }: ExportPanelProps) {
  const [exportType, setExportType] = useState<"code" | "json" | "pubspec">("code")
  const [copied, setCopied] = useState(false)

  const handleCopyCode = () => {
    navigator.clipboard.writeText(getExportContent())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const content = getExportContent()
    const filename = getExportFilename()
    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)

    const a = document.createElement("a")
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const getExportContent = () => {
    switch (exportType) {
      case "code":
        return code
      case "json":
        return JSON.stringify(elements, null, 2)
      case "pubspec":
        return `name: flutter_ui_app
description: A Flutter UI application generated by Flutter UI Designer.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
`
      default:
        return ""
    }
  }

  const getExportFilename = () => {
    switch (exportType) {
      case "code":
        return "main.dart"
      case "json":
        return "design.json"
      case "pubspec":
        return "pubspec.yaml"
      default:
        return "export.txt"
    }
  }

  const handleExportZip = () => {
    alert("This would export a ZIP file with the complete Flutter project.")
    // In a real implementation, this would create a ZIP file with all necessary files
  }

  return (
    <div className="flex flex-1 flex-col overflow-hidden bg-gray-100">
      <div className="flex items-center justify-between border-b border-gray-200 bg-white p-4">
        <h2 className="text-lg font-semibold">Export</h2>
        <div className="flex items-center space-x-2">
          <select
            value={exportType}
            onChange={(e) => setExportType(e.target.value as any)}
            className="rounded-md border border-gray-300 px-3 py-1 text-sm"
          >
            <option value="code">Flutter Code</option>
            <option value="json">JSON Design</option>
            <option value="pubspec">pubspec.yaml</option>
          </select>
          <button
            onClick={handleCopyCode}
            className="rounded-md bg-blue-100 px-3 py-1 text-sm font-medium text-blue-700 hover:bg-blue-200"
          >
            {copied ? "Copied!" : "Copy"}
          </button>
          <button
            onClick={handleDownload}
            className="rounded-md bg-blue-100 px-3 py-1 text-sm font-medium text-blue-700 hover:bg-blue-200"
          >
            Download
          </button>
        </div>
      </div>

      <div className="flex flex-1 flex-col overflow-hidden p-4">
        <pre className="flex-1 overflow-auto rounded-lg bg-gray-800 p-4 text-sm text-white">
          <code>{getExportContent()}</code>
        </pre>

        <div className="mt-4 flex justify-end">
          <button
            onClick={handleExportZip}
            className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
          >
            Export Complete Project (ZIP)
          </button>
        </div>
      </div>
    </div>
  )
}
